### ISSUE TITLE
Support for LanguageClient-Neovim (and/or coc.nvim)

### ISSUE THREAD

**Issue by smolck** [vhakulinen/gnvim-lsp#1]
Would it be possible to add support for LanguageClient-Neovim (and/or coc.nvim)? I am happy to help with the implementation if needed/wanted; it would be nice to support other LSPs.

**Comment by vhakulinen** [comment]
Technically, sure. Otherwise, I'm not quite sure how I would go about that. The code here in this plugin is _really_ simple, and I would preferably see other plugins adding support for other lsp clients - this will keep each one focused.

**Comment by smolck** [comment]
Sounds good. I'll try my hand at making an equivalent plugin for LanguageClient-Neovim at some point (hopefully). If I get one working well, would you be interested in updating GNvim's README to include a link to it?

**Comment by vhakulinen** [comment]
> ...would you be interested in updating GNvim's README to include a link to it?

Sure.
